name: Deno Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Start server in background
        run: |
          deno run --allow-all main.ts &
          SERVER_PID=$!
          sleep 3
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV

      - name: Run tests
        run: deno test --allow-all

      - name: Stop server
        if: always()
        run: kill $SERVER_PID || true
